spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: pg1.vpc.cloudera.com:9092
          requiredAcks: -1
          producerProperties:
            retries: 3
            enable.idempotence: true
            max.in.flight.requests.per.connection: 2
            delivery.timeout.ms: 20000
            request.timeout.ms: 10000


      kafka.bindings.people-out.producer:
        configuration:
          client.id: producer-people
      kafka.bindings.people-in.consumer:
        autoCommitOffset: false
      kafka.bindings.metricbeat-log-in.consumer:
        autoCommitOffset: false
      bindings:
        metricbeat-log-in:
          destination: logs-7.5.2
          group: metric-log-1
          contentType: application/json
          consumer.partitioned: true

        greetings-in:
          destination: greetings
          contentType: application/json
        greetings-out:
          destination: greetings
          contentType: application/json
        people-in:
          destination: people
          group: consumer-group-people
        people-out:
          destination: people
          producer:
            sync: true

          #contentType: application/json

  profiles:
    active: dev

server:
  port: 8080

management.endpoint.metrics.enabled: true
management.endpoints.web.exposure.include: "*"
management.endpoint.health.show-details: always

info:
  app:
    name: kafka info
